---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to docker
        uses: docker/login-action
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: docker/checkout
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"


